# monthly configs for client bare metal provisioning quotes
8260-192:
  hostname: "bm-8260-192"
  domain: "testing.com"
  package-keyname: "DUAL_INTEL_XEON_PROC_CASCADE_LAKE_SCALABLE_FAMILY_12_DRIVES"
  server: "INTEL_INTEL_XEON_8260_2_40"
  os: "OS_NO_OPERATING_SYSTEM"
  location: "SANJOSE04"
  ram: "RAM_192_GB_DDR4_2133_ECC_REG"
  disk-controller: "DISK_CONTROLLER_NONRAID"
  first-hard-drive: "HARD_DRIVE_960GB_SSD_SED_5DWPD"
  public-bandwidth: "BANDWIDTH_0_GB"
  uplink-port-speeds: "10_GBPS_REDUNDANT_PRIVATE_NETWORK_UPLINKS"
  power-supply: "REDUNDANT_POWER_SUPPLY"
  monitoring: "MONITORING_HOST_PING"
  response: "AUTOMATED_NOTIFICATION"
  billing: "monthly"
  remote-management: "REBOOT_KVM_OVER_IP"
  primary-ip-addresses: "1_IP_ADDRESS"
  vpn-management: "UNLIMITED_SSL_VPN_USERS_1_PPTP_VPN_USER_PER_ACCOUNT"
  notification: "NOTIFICATION_EMAIL_AND_TICKET"

7642-1:
  hostname: "bm-7642-1"
  domain: "testing.com"
  package-keyname: "2U_AMD_2ND_GEN_EPYC"
  server: "DUAL_AMD_EPYC_7642_2_30"
  os: "OS_NO_OPERATING_SYSTEM"
  location: "SANJOSE04"
  ram: "RAM_1_TB_GB_DDR4_2933_ECC_REG"
  disk-controller: "DISK_CONTROLLER_NONRAID"
  first-hard-drive: "HARD_DRIVE_960GB_SSD_SED_5DWPD"
  public-public-bandwidth: "BANDWIDTH_0_GB"
  uplink-port-speeds: "10_GBPS_REDUNDANT_PRIVATE_NETWORK_UPLINKS"
  power-supply: "REDUNDANT_POWER_SUPPLY"
  monitoring: "MONITORING_HOST_PING"
  response: "AUTOMATED_NOTIFICATION"
  billing: "monthly"
  remote-management: "REBOOT_KVM_OVER_IP"
  primary-ip-addresses: "1_IP_ADDRESS"
  vpn-management: "UNLIMITED_SSL_VPN_USERS_1_PPTP_VPN_USER_PER_ACCOUNT"
  notification: "NOTIFICATION_EMAIL_AND_TICKET"

7642-512:
  hostname: "bm-7642-512"
  domain: "testing.com"
  package-keyname: "2U_AMD_2ND_GEN_EPYC"
  server: "DUAL_AMD_EPYC_7642_2_30"
  os: "OS_NO_OPERATING_SYSTEM"
  location: "SANJOSE04"
  ram: "RAM_512_GB_DDR4_2933_ECC_REG"
  disk-controller: "DISK_CONTROLLER_NONRAID"
  first-hard-drive: "HARD_DRIVE_960GB_SSD_SED_5DWPD"
  public-bandwidth: "BANDWIDTH_0_GB"
  uplink-port-speeds: "10_GBPS_REDUNDANT_PRIVATE_NETWORK_UPLINKS"
  power-supply: "REDUNDANT_POWER_SUPPLY"
  monitoring: "MONITORING_HOST_PING"
  response: "AUTOMATED_NOTIFICATION"
  billing: "monthly"
  remote-management: "REBOOT_KVM_OVER_IP"
  primary-ip-addresses: "1_IP_ADDRESS"
  vpn-management: "UNLIMITED_SSL_VPN_USERS_1_PPTP_VPN_USER_PER_ACCOUNT"
  notification: "NOTIFICATION_EMAIL_AND_TICKET"

7642-256:
  hostname: "bm-7642-256"
  domain: "testing.com"
  package-keyname: "2U_AMD_2ND_GEN_EPYC"
  server: "DUAL_AMD_EPYC_7642_2_30"
  os: "OS_NO_OPERATING_SYSTEM"
  location: "SANJOSE04"
  ram: "RAM_262144_GB_DDR4_2933_ECC_REG"
  disk-controller: "DISK_CONTROLLER_NONRAID"
  first-hard-drive: "HARD_DRIVE_960GB_SSD_SED_5DWPD"
  public-bandwidth: "BANDWIDTH_0_GB"
  uplink-port-speeds: "10_GBPS_REDUNDANT_PRIVATE_NETWORK_UPLINKS"
  power-supply: "REDUNDANT_POWER_SUPPLY"
  monitoring: "MONITORING_HOST_PING"
  response: "AUTOMATED_NOTIFICATION"
  billing: "monthly"
  remote-management: "REBOOT_KVM_OVER_IP"
  primary-ip-addresses: "1_IP_ADDRESS"
  vpn-management: "UNLIMITED_SSL_VPN_USERS_1_PPTP_VPN_USER_PER_ACCOUNT"
  notification: "NOTIFICATION_EMAIL_AND_TICKET"

6248-768-12:
  hostname: "bm-6248-768-12"
  domain: "testing.com"
  package-keyname: "DUAL_INTEL_XEON_PROC_CASCADE_LAKE_SCALABLE_FAMILY_12_DRIVES"
  server: "INTEL_INTEL_XEON_6248_2_60"
  os: "OS_NO_OPERATING_SYSTEM"
  location: "SANJOSE04"
  ram: "RAM_768_GB_DDR4_2133_ECC_REG"
  disk-controller: "DISK_CONTROLLER_NONRAID"
  first-hard-drive: "HARD_DRIVE_960GB_SSD_SED_5DWPD"
  public-bandwidth: "BANDWIDTH_0_GB"
  uplink-port-speeds: "10_GBPS_REDUNDANT_PRIVATE_NETWORK_UPLINKS"
  power-supply: "REDUNDANT_POWER_SUPPLY"
  monitoring: "MONITORING_HOST_PING"
  response: "AUTOMATED_NOTIFICATION"
  billing: "monthly"
  remote-management: "REBOOT_KVM_OVER_IP"
  primary-ip-addresses: "1_IP_ADDRESS"
  vpn-management: "UNLIMITED_SSL_VPN_USERS_1_PPTP_VPN_USER_PER_ACCOUNT"
  notification: "NOTIFICATION_EMAIL_AND_TICKET"

8260-768:
  hostname: "bm-8260-768"
  domain: "testing.com"
  package-keyname: "DUAL_INTEL_XEON_PROC_CASCADE_LAKE_SCALABLE_FAMILY_12_DRIVES"
  server: "INTEL_INTEL_XEON_8260_2_40"
  os: "OS_NO_OPERATING_SYSTEM"
  location: "SANJOSE04"
  ram: "RAM_768_GB_DDR4_2133_ECC_REG"
  disk-controller: "DISK_CONTROLLER_NONRAID"
  first-hard-drive: "HARD_DRIVE_960GB_SSD_SED_5DWPD"
  public-bandwidth: "BANDWIDTH_0_GB"
  uplink-port-speeds: "10_GBPS_REDUNDANT_PRIVATE_NETWORK_UPLINKS"
  power-supply: "REDUNDANT_POWER_SUPPLY"
  monitoring: "MONITORING_HOST_PING"
  response: "AUTOMATED_NOTIFICATION"
  billing: "monthly"
  remote-management: "REBOOT_KVM_OVER_IP"
  primary-ip-addresses: "1_IP_ADDRESS"
  vpn-management: "UNLIMITED_SSL_VPN_USERS_1_PPTP_VPN_USER_PER_ACCOUNT"
  notification: "NOTIFICATION_EMAIL_AND_TICKET"

6248-384:
  hostname: "bm-6248-384"
  domain: "testing.com"
  package-keyname: "DUAL_INTEL_XEON_PROCESSOR_CASCADE_LAKE_SCALABLE_FAMILY_4_DRIVES"
  server: "INTEL_XEON_6248_2_50"
  os: "OS_NO_OPERATING_SYSTEM"
  location: "SANJOSE04"
  ram: "RAM_384_GB_DDR4_2133_ECC_REG"
  disk-controller: "DISK_CONTROLLER_NONRAID"
  first-hard-drive: "HARD_DRIVE_960GB_SSD_SED_5DWPD"
  public-bandwidth: "BANDWIDTH_0_GB"
  uplink-port-speeds: "10_GBPS_REDUNDANT_PRIVATE_NETWORK_UPLINKS"
  power-supply: "REDUNDANT_POWER_SUPPLY"
  monitoring: "MONITORING_HOST_PING"
  response: "AUTOMATED_NOTIFICATION"
  billing: "monthly"
  remote-management: "REBOOT_KVM_OVER_IP"
  primary-ip-addresses: "1_IP_ADDRESS"
  vpn-management: "UNLIMITED_SSL_VPN_USERS_1_PPTP_VPN_USER_PER_ACCOUNT"
  notification: "NOTIFICATION_EMAIL_AND_TICKET"

6248-768-4:
  hostname: "bm-6248-768-4"
  domain: "testing.com"
  package-keyname: "DUAL_INTEL_XEON_PROCESSOR_CASCADE_LAKE_SCALABLE_FAMILY_4_DRIVES"
  server: "INTEL_XEON_6248_2_50"
  os: "OS_NO_OPERATING_SYSTEM"
  location: "SANJOSE04"
  ram: "RAM_768_GB_DDR4_2133_ECC_REG"
  disk-controller: "DISK_CONTROLLER_NONRAID"
  first-hard-drive: "HARD_DRIVE_960GB_SSD_SED_5DWPD"
  public-bandwidth: "BANDWIDTH_0_GB"
  uplink-port-speeds: "10_GBPS_REDUNDANT_PRIVATE_NETWORK_UPLINKS"
  power-supply: "REDUNDANT_POWER_SUPPLY"
  monitoring: "MONITORING_HOST_PING"
  response: "AUTOMATED_NOTIFICATION"
  billing: "monthly"
  remote-management: "REBOOT_KVM_OVER_IP"
  primary-ip-addresses: "1_IP_ADDRESS"
  vpn-management: "UNLIMITED_SSL_VPN_USERS_1_PPTP_VPN_USER_PER_ACCOUNT"
  notification: "NOTIFICATION_EMAIL_AND_TICKET"
